//! Resolves calls in complete bounded scalar helper tables.

module wheeler.compiler.scalar_helper_resolution;

import wheeler.compiler.ir;
import wheeler.compiler.resolved_helper_validity;
import wheeler.compiler.scalar_helper_call_resolution;
import wheeler.compiler.scalar_helper_parsing;
import wheeler.compiler.scalar_helper_tables;

classical class ScalarHelperResolution {
  /// Carries one complete scalar helper table after call resolution.
  public record ResolvedScalarHelperTable(
    long helperCount,
    HelperBody first,
    HelperBody second,
    HelperBody third,
    HelperBody fourth,
    HelperBody fifth,
    HelperBody sixth,
    HelperBody seventh,
    HelperBody eighth,
    HelperBody ninth,
    HelperBody tenth,
    HelperBody eleventh,
    HelperBody twelfth,
    HelperBody thirteenth,
    HelperBody fourteenth,
    HelperBody fifteenth,
    HelperBody sixteenth,
    HelperBody seventeenth,
    HelperBody eighteenth,
    HelperBody nineteenth,
    HelperBody twentieth,
    HelperBody twentyFirst,
    HelperBody twentySecond,
    HelperBody twentyThird,
    boolean valid
  ) {}

  private ResolvedScalarHelperTable invalidResolvedTable() {
    return new ResolvedScalarHelperTable(
      0,
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      emptyHelperBody(),
      false
    );
  }

  /// Resolves every bounded helper call without publishing a partial table.
  public ResolvedScalarHelperTable resolveScalarHelperTable(
    borrow utf8 source,
    ScalarHelperTable parsed
  ) {
    if (parsed.valid) {} else {
      return invalidResolvedTable();
    }

    long helperCount = parsed.helperCount;
    HelperBody firstBody = parsed.first;
    HelperBody secondBody = parsed.second;
    HelperBody thirdBody = parsed.third;
    HelperBody fourthBody = parsed.fourth;
    HelperBody fifthBody = parsed.fifth;
    HelperBody sixthBody = parsed.sixth;
    HelperBody seventhBody = parsed.seventh;
    HelperBody eighthBody = parsed.eighth;
    HelperBody ninthBody = parsed.ninth;
    HelperBody tenthBody = parsed.tenth;
    HelperBody eleventhBody = parsed.eleventh;
    HelperBody twelfthBody = parsed.twelfth;
    HelperBody thirteenthBody = parsed.thirteenth;
    HelperBody fourteenthBody = parsed.fourteenth;
    HelperBody fifteenthBody = parsed.fifteenth;
    HelperBody sixteenthBody = parsed.sixteenth;
    HelperBody seventeenthBody = parsed.seventeenth;
    HelperBody eighteenthBody = parsed.eighteenth;
    HelperBody nineteenthBody = parsed.nineteenth;
    HelperBody twentiethBody = parsed.twentieth;
    HelperBody twentyFirstBody = parsed.twentyFirst;
    HelperBody twentySecondBody = parsed.twentySecond;
    HelperBody twentyThirdBody = parsed.twentyThird;
    if (
      uniqueHelpers(
        source,
        firstBody,
        secondBody,
        thirdBody,
        fourthBody,
        fifthBody,
        sixthBody,
        seventhBody,
        eighthBody,
        ninthBody,
        tenthBody,
        eleventhBody,
        twelfthBody,
        thirteenthBody,
        fourteenthBody,
        fifteenthBody,
        sixteenthBody,
        seventeenthBody,
        eighteenthBody,
        nineteenthBody,
        twentiethBody,
        twentyFirstBody,
        twentySecondBody,
        twentyThirdBody,
        helperCount
      )
    ) {} else {
      return invalidResolvedTable();
    }

    ResolvedHelperBody firstResolved = resolvedHelperBody(
      source,
      firstBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody secondResolved = resolvedHelperBody(
      source,
      secondBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody thirdResolved = resolvedHelperBody(
      source,
      thirdBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody fourthResolved = resolvedHelperBody(
      source,
      fourthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody fifthResolved = resolvedHelperBody(
      source,
      fifthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody sixthResolved = resolvedHelperBody(
      source,
      sixthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody seventhResolved = resolvedHelperBody(
      source,
      seventhBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody eighthResolved = resolvedHelperBody(
      source,
      eighthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody ninthResolved = resolvedHelperBody(
      source,
      ninthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody tenthResolved = resolvedHelperBody(
      source,
      tenthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody eleventhResolved = resolvedHelperBody(
      source,
      eleventhBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody twelfthResolved = resolvedHelperBody(
      source,
      twelfthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody thirteenthResolved = resolvedHelperBody(
      source,
      thirteenthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody fourteenthResolved = resolvedHelperBody(
      source,
      fourteenthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody fifteenthResolved = resolvedHelperBody(
      source,
      fifteenthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody sixteenthResolved = resolvedHelperBody(
      source,
      sixteenthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody seventeenthResolved = resolvedHelperBody(
      source,
      seventeenthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody eighteenthResolved = resolvedHelperBody(
      source,
      eighteenthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody nineteenthResolved = resolvedHelperBody(
      source,
      nineteenthBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody twentiethResolved = resolvedHelperBody(
      source,
      twentiethBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody twentyFirstResolved = resolvedHelperBody(
      source,
      twentyFirstBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody twentySecondResolved = resolvedHelperBody(
      source,
      twentySecondBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    ResolvedHelperBody twentyThirdResolved = resolvedHelperBody(
      source,
      twentyThirdBody,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      helperCount
    );
    if (
      resolvedHelpersValid(
        helperCount,
        firstResolved,
        secondResolved,
        thirdResolved,
        fourthResolved,
        fifthResolved,
        sixthResolved,
        seventhResolved,
        eighthResolved,
        ninthResolved,
        tenthResolved,
        eleventhResolved,
        twelfthResolved,
        thirteenthResolved,
        fourteenthResolved,
        fifteenthResolved,
        sixteenthResolved,
        seventeenthResolved,
        eighteenthResolved,
        nineteenthResolved,
        twentiethResolved,
        twentyFirstResolved,
        twentySecondResolved,
        twentyThirdResolved
      )
    ) {} else {
      return invalidResolvedTable();
    }

    firstBody = firstResolved.body;
    secondBody = secondResolved.body;
    thirdBody = thirdResolved.body;
    fourthBody = fourthResolved.body;
    fifthBody = fifthResolved.body;
    sixthBody = sixthResolved.body;
    seventhBody = seventhResolved.body;
    eighthBody = eighthResolved.body;
    ninthBody = ninthResolved.body;
    tenthBody = tenthResolved.body;
    eleventhBody = eleventhResolved.body;
    twelfthBody = twelfthResolved.body;
    thirteenthBody = thirteenthResolved.body;
    fourteenthBody = fourteenthResolved.body;
    fifteenthBody = fifteenthResolved.body;
    sixteenthBody = sixteenthResolved.body;
    seventeenthBody = seventeenthResolved.body;
    eighteenthBody = eighteenthResolved.body;
    nineteenthBody = nineteenthResolved.body;
    twentiethBody = twentiethResolved.body;
    twentyFirstBody = twentyFirstResolved.body;
    twentySecondBody = twentySecondResolved.body;
    twentyThirdBody = twentyThirdResolved.body;

    return new ResolvedScalarHelperTable(
      helperCount,
      firstBody,
      secondBody,
      thirdBody,
      fourthBody,
      fifthBody,
      sixthBody,
      seventhBody,
      eighthBody,
      ninthBody,
      tenthBody,
      eleventhBody,
      twelfthBody,
      thirteenthBody,
      fourteenthBody,
      fifteenthBody,
      sixteenthBody,
      seventeenthBody,
      eighteenthBody,
      nineteenthBody,
      twentiethBody,
      twentyFirstBody,
      twentySecondBody,
      twentyThirdBody,
      true
    );
  }
}
